### ISSUE TITLE
Mac Scapy Error

### ISSUE THREAD

**Issue by AppleTechy** [andreafabrizi/rtmpSnoop#21]
When I try and run the script on my Mac(El Capitan) it give me this error `sudo python /Volumes/Storage/Rtmp/rtmpSnoop/rtmpSnoop.py -h
Password:
Traceback (most recent call last):
  File "/Volumes/Storage/Rtmp/rtmpSnoop/rtmpSnoop.py", line 26, in <module>
    from scapy.all import *
ImportError: No module named scapy.all`
Any ideas?

**Comment by andreafabrizi** [comment]
You need to install scapy

**Comment by AppleTechy** [comment]
I know I have to install scapy. But when I ran `pip install scapy` I run
into an error saying something about setup.egg.py or something. Any ideas?
